package javascriptExample;


import java.util.List;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.Test;

//ctrl+shift+O ----- add or remove unused imports

//Generated by Selenium IDE

public class WebTableExample3 {
	private WebDriver driver;

	@Test
	public void recaptest() throws Exception {
		
		driver = new ChromeDriver();
		driver.manage().window().maximize();
		
		
		driver.get("https://demoqa.com/automation-practice-form");
		
		
		
		
		List<WebElement> chk_all = driver.findElements(By.xpath("//table/descendant::td/input"));
		
		for (int i = 0; i < chk_all.size(); i++) {
			
			chk_all.get(i).click();
			
		}
		
		
		
		
		//driver.findElement(By.cssSelector("button#submit")).click();
		
//		driver.get("https://www.hyrtutorials.com/p/add-padding-to-containers.html");
//		
//		
//		
////		JavaScript example
//	
//		
//		
//		
//		
//		driver.findElement(By.xpath("//td[text()='Helen Bennett']//preceding-sibling::td/input")).click();
		
		
		
		
	}
}
