package exercise;

import org.junit.Assert;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

//ctrl+shift+O ----- add or remove unused imports

//Generated by Selenium IDE

public class ExampleSIDE {
	private WebDriver driver;

	@Test
	public void recaptest() throws Exception {
		
		driver = new ChromeDriver();
		driver.manage().window().maximize();
		driver.get("https://www.irctc.co.in/nget/train-search");
		
		
		driver.findElement(By.partialLinkText("HOTELS")).click();

		Thread.sleep(5000);
		
		//driver.close(); // close the current focus window
		

		
		driver.quit();	//close all the instance opened by driver
	}
}
