package WebTable_XpathAxis;


import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.Test;

//ctrl+shift+O ----- add or remove unused imports

//Generated by Selenium IDE

public class WebTableExample {
	private WebDriver driver;

	@Test
	public void recaptest() throws Exception {
		
		driver = new ChromeDriver();
		driver.manage().window().maximize();
		driver.get("https://www.hyrtutorials.com/p/add-padding-to-containers.html");
		
		
		
//		JavaScript example
	
		
		
		
		
		driver.findElement(By.xpath("//td[text()='Helen Bennett']//preceding-sibling::td/input")).click();
		
		
		
		
	}
}
