package takeScreenShotExample;


import java.io.File;
import java.io.IOException;
import java.util.List;

import org.apache.commons.io.FileUtils;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.Test;

//ctrl+shift+O ----- add or remove unused imports

//Generated by Selenium IDE

public class AmazonApp {
	private WebDriver driver;

	@Test
	public void verifySearchItem() throws Exception {
		
		driver = new ChromeDriver();
		driver.manage().window().maximize();
		
		
		driver.get("https://www.amazon.in/");
		
		WebElement txt_searchbox = driver.findElement(By.cssSelector("#twotabsearchtextbox"));
		WebElement btn_Go = driver.findElement(By.cssSelector("[id=\"nav-search-submit-button\"]"));
		
		
		
		txt_searchbox.sendKeys("iphone 15 pro");
		btn_Go.click();
		
		
		
		Thread.sleep(3000);
		
		
		//takescreenshot
		
		
//		TakesScreenshot ts = ((TakesScreenshot) driver);
		
		
		
//		File screenshotFile = ((TakesScreenshot) driver).getScreenshotAs(OutputType.FILE);				///captured a screenshot ----
//		
//		
//		File targetLocation = new File("./IBM_screenshot\\AmazonSeachProduct.png");
//		
//		
//		
//		FileUtils.copyFile(screenshotFile, targetLocation);
		
		captureScreens("Amazon_verifySearchItem_new");
		
		
		
	}
	
	
	
	public void captureScreens(String fileName) throws Exception {
		
		File screenshotFile = ((TakesScreenshot) driver).getScreenshotAs(OutputType.FILE);				///captured a screenshot ----
		
		
		File targetLocation = new File(".\\IBM_screenshot\\"+fileName+".png");
		
		
		
		FileUtils.copyFile(screenshotFile, targetLocation);
		
	}
	
	
	
	
	
	
}
